### PR TITLE
v1.3.2 / DE-165 | Package Verbosity Options

### PR DESCRIPTION
**Pull request by Geoiv**
### Added
- Session-level configuration Functionality
- Verbosity option: disable all non-logging output, for use in notebooks or pipelines.

### CODE REVIEW

**Comment by Geoiv** [comment]
Tests are currently failing, but it doesn't appear to have anything to do with this functionality. I believe it has to do with an update to `pyarrow`, since it only affects the tests for the `feather` format - will investigate.

**Review by frankiezeager — APPROVED** [review]
Love this. It will make it suuuuper easy for serverless functions to not use the verbose option, since you can set global env vars in the .yaml file. Haven't played around enough with airflow to know if this is true there, but at the very worst we could just do an os.environ['verbose']=False or whatever.

**Comment by Geoiv** [comment]
@frankiezeager setting defaults using envvars isn't currently supported, but I'm happy to add that if you'd like! Would be really easy to do so

**Review by freytheviking — APPROVED** [review]
Love it :).

**Pull request merged**
